import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Focus Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider
          appearance={{
            baseTheme: "simple",
            variables: { colorPrimary: "#859FD5" },
          }}
        >
          <NextTopLoader color="#5477BE" showSpinner={false} />

          <body>{children}</body>
        </ClerkProvider>
      </body>
    </html>
  );
}
