import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import NextTopLoader from "nextjs-toploader";
import { cn } from "@/lib/utils"; // Assuming you have a cn utility for conditional class names
import { Toaster } from "sonner";

// Configure Manrope font
const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Focus Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(manrope.variable, "bg-background text-foreground")}>
        <ClerkProvider
          appearance={{
            baseTheme: "simple",
            variables: { colorPrimary: "#859FD5" },
          }}
        >
          <NextTopLoader color="#5477BE" showSpinner={false} />
          {children}
          <Toaster position="bottom-right" richColors />
        </ClerkProvider>
      </body>
    </html>
  );
}
